version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    ssteps:
      - checkout
      - run:
          name: INIT
          command: terraform init -input=false
      - run:
          name: PLAN
          command: terraform plan -out=tfplan -input=false -var 'db_password=$DB_PASSWORD'
      - run:
          name: APPLY
          command: terraform apply -input=false tfplan
